### PR TITLE
Manual ruby 3.1 migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Follow-up for #17 for the other platforms

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I'm not sure how to skip the ruby2.6 build for Windows .. do you happen to know what the selector should look like @wolfv @traversaro?

**Comment by traversaro** [comment]
> I'm not sure how to skip the ruby2.6 build for Windows .. do you happen to know what the selector should look like @wolfv @traversaro?

I think there is something wrong in the migrator itself and how it interacts with the existing conda-forge-pinning pin for ruby, see for example https://github.com/conda-forge/gz-tools2-feedstock/pull/8 .

fyi @conda-forge/ruby

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I copied the strategied that worked in https://github.com/conda-forge/gz-tools2-feedstock/pull/8 .

**Review by traversaro — APPROVED** [review]

**Pull request merged**
