### PR TITLE
Backport patches for full Windows support

### PR DESCRIPTION
**Pull request by traversaro**
Backport https://github.com/ignitionrobotics/ign-tools/pull/73 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Seems like the `ignition-tools-backward.lib` is not being created / installed?

**Comment by traversaro** [comment]
> Seems like the `ignition-tools-backward.lib` is not being created / installed?

I think that is ok, we can skip the test.

**Comment by traversaro** [comment]
> > Seems like the `ignition-tools-backward.lib` is not being created / installed?
> 
> I think that is ok, we can skip the test.

Actually I am not sure how much this is ok, but as long as it silence the warning, it is probably a good first step.

**Pull request merged**
