### PR TITLE
Add ruby run dependency

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/libignition-msgs1-feedstock/pull/15 where test failures occur when ruby is not installed.

Thanks @traversaro for the suggestion

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by wolfv** [comment]
Should it be a runtime dependency or a run_exports? Maybe run dep is enough?

**Comment by Tobias-Fischer** [comment]
Good call @wolfv. Changed.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@Tobias-Fischer I guess this is good to go now, right?

**Comment by Tobias-Fischer** [comment]
Yes:)

**Pull request merged**
